name: mbark_iptv
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.7+8

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  cached_network_image: ^3.4.1
  responsive_sizer: ^3.3.1
  awesome_snackbar_content: ^0.1.3
  google_fonts: ^6.2.1
  flutter_rating_bar: ^4.0.1
  readmore: ^3.0.0
  filling_slider: ^0.0.3
  loading_animation_widget: ^1.2.1
  wakelock: ^0.6.2


  #Logic
  azul_envato_checker: ^0.0.6+6
  flutter_bloc: ^8.1.6
  get: ^4.6.6
  intl: ^0.19.0
  get_storage: ^2.1.1
  url_launcher: ^6.3.0
 # wakelock: ^0.6.2
  #perfect_volume_control: ^1.0.5
  volume_controller: ^2.0.8
  screen_brightness_util: ^0.0.3

  #M3U
  flutter_vlc_player: ^7.4.2
  pod_player: ^0.2.2



  #Http
  dio: ^5.6.0
  google_mobile_ads: ^5.1.0


dependency_overrides:
  win32: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/images/

